// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ZEusIJt4Qlg4N7J6JsW1WMAKNn73s00',
    appId: '1:86286543718:web:61d551f330a0fd2dbb76a7',
    messagingSenderId: '86286543718',
    projectId: 'dentassure-360',
    authDomain: 'dentassure-360.firebaseapp.com',
    storageBucket: 'dentassure-360.firebasestorage.app',
    measurementId: 'G-5G7JLPP5NC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAubZNKnCxkb4foDotY5-0zNiSr2X_6Ibc',
    appId: '1:86286543718:android:81524a769c591a0cbb76a7',
    messagingSenderId: '86286543718',
    projectId: 'dentassure-360',
    storageBucket: 'dentassure-360.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAh5G7VObyBeJ9JwN2rEUwWT6ziys20xws',
    appId: '1:86286543718:ios:abfa8081640d9a86bb76a7',
    messagingSenderId: '86286543718',
    projectId: 'dentassure-360',
    storageBucket: 'dentassure-360.firebasestorage.app',
    iosBundleId: 'com.example.dentassure360',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAh5G7VObyBeJ9JwN2rEUwWT6ziys20xws',
    appId: '1:86286543718:ios:abfa8081640d9a86bb76a7',
    messagingSenderId: '86286543718',
    projectId: 'dentassure-360',
    storageBucket: 'dentassure-360.firebasestorage.app',
    iosBundleId: 'com.example.dentassure360',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9ZEusIJt4Qlg4N7J6JsW1WMAKNn73s00',
    appId: '1:86286543718:web:edcf13ee8fa5fbf8bb76a7',
    messagingSenderId: '86286543718',
    projectId: 'dentassure-360',
    authDomain: 'dentassure-360.firebaseapp.com',
    storageBucket: 'dentassure-360.firebasestorage.app',
    measurementId: 'G-7CJWGZEWN6',
  );
}
